import Script from 'next/script';
import '../styles/globals.scss'
import UtilityCookies from '../components/UtilityCookies';
import Footer from '../components/Footer';
import PageWrapper from '../components/PageWrapper';
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="it">

      <Script async src="https://www.googletagmanager.com/gtag/js?id=G-QXT3DWCP13"></Script>
      <Script id="google-analytics">
        {`

          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}

          gtag('js', new Date());
        
          gtag('config', 'G-QXT3DWCP13');

 
          gtag('consent', 'default', {
            'ad_storage': 'denied',
            'ad_user_data': 'denied',
            'ad_personalization': 'denied',
            'analytics_storage': 'denied'
          });
          
        `}
      </Script>
      {/* <Script src="https://groot.mailerlite.com/js/w/webforms.min.js?v2d8fb22bb5b3677f161552cd9e774127" type="text/javascript"></Script>
      <Script>
        fetch("https://assets.mailerlite.com/jsonp/863030/forms/115595877754603214/takel")
      </Script> */}
      <body className={`ciao`}>
        <PageWrapper>
        {children}
        <Footer />
        </PageWrapper>
        <UtilityCookies />
      </body>
    </html>
  );
}
